services:
  - type: web
    name: gold-signal
    runtime: python
    env:
      PYTHON_VERSION: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
